version: '3.8'

services:
  airflow:
    build: .
    container_name: airflow_etl
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    environment:
      - LOAD_EXAMPLES=no

